import {
  AccordionPage,
  AlertPage,
  BadgePage,
  ButtonPage,
  CardPage,
  CollapsiblePage,
  ComponentPropertiesPage,
  DropdownMenuPage,
  FlexPage,
  HoverCardPage,
  InputPage,
  PopoverPage,
  SelectPage,
  SeparatorPage,
  SheetPage,
  SidebarPage,
  SkeletonPage,
  TabsPage,
  ThemeProviderPage,
  TooltipPage,
} from '@/pages';

export const leftMenuRoutes = {
  '/components/library': <ComponentPropertiesPage />,
  '/components/theme-provider': <ThemeProviderPage />,
  '/components/button': <ButtonPage />,
  '/components/flex': <FlexPage />,
  '/components/dropdown-menu': <DropdownMenuPage />,
  '/components/sidebar': <SidebarPage />,
  '/components/input': <InputPage />,
  '/components/select': <SelectPage />,
  '/components/popover': <PopoverPage />,
  '/components/tabs': <TabsPage />,
  '/components/tooltip': <TooltipPage />,
  '/components/collapsible': <CollapsiblePage />,
  '/components/sheet': <SheetPage />,
  '/components/separator': <SeparatorPage />,
  '/components/card': <CardPage />,
  '/components/hover-card': <HoverCardPage />,
  '/components/accordion': <AccordionPage />,
  '/components/skeleton': <SkeletonPage />,
  '/components/alert': <AlertPage />,
  '/components/badge': <BadgePage />,
};
